### ISSUE TITLE
Use unique DCC id to match DCCs from the stats/ endpoints with those in the user's favorites.

### ISSUE THREAD

**Issue by jrchudy** [nih-cfde/dashboard#101]
@jonathancrabtree during the UX call this morning, you mentioned something about this issue while we were discussing what might be left from the changes for [this comment in issue 96](https://github.com/nih-cfde/dashboard/issues/96#issuecomment-906488502). Could you update the title and description for this issue?

**Comment by jonathancrabtree** [comment]
Currently on the personalized dashboard one of the stats API endpoints is used to populate the main graph and figure out which DCCs to create checkboxes for. However, determining which checkboxes are checked initially is done by looking at the user's favorites. The matching of DCCs between the checkboxes and the favorites should be done using unique DCC id, not the DCC abbreviation.

**Comment by mschor** [comment]
After looking into this a little bit, I don't believe we're getting back the DCC IDs when getting the favorites (although I may be mistaken).
For the 2 favorite DCCs I have, I'm getting back these JSONs from the cfde-deriva call:
```
{'RID': '9FP', 'RCT': '2021-03-23T19:10:55.66419+00:00', 'RMT': '2021-08-17T18:51:11.92502+00:00', 'RCB': 'https://auth.globus.org/0ca84535-2f0b-4e25-9b0a-fba1e6c5008c', 'RMB': 'https://auth.globus.org/e4590450-f987-41ad-93e9-2ae2bd0303c3', 'id': 'cfde_registry_dcc:exrna', 'dcc_name': 'Extracellular RNA Communication', 'description': 'The Extracellular RNA Communication (ERC) program is working to understand exRNA biology and accelerate development of exRNAs as potential therapeutics and diagnostics.', 'contact_email': 'mattr@bcm.edu', 'contact_name': 'Matt Roth', 'dcc_url': 'https://exrna.org/', 'dcc_abbreviation': 'ERCC_DCC'}
{'RID': 'C8E', 'RCT': '2021-04-14T16:01:50.189046+00:00', 'RMT': '2021-08-17T18:51:11.92502+00:00', 'RCB': 'https://auth.globus.org/e4590450-f987-41ad-93e9-2ae2bd0303c3', 'RMB': 'https://auth.globus.org/e4590450-f987-41ad-93e9-2ae2bd0303c3', 'id': 'cfde_registry_dcc:sparc', 'dcc_name': 'Stimulating Peripheral Activity to Relieve Conditions', 'description': 'The Common Fund’s Stimulating Peripheral Activity to Relieve Conditions (SPARC) program seeks to accelerate development of therapeutic devices that modulate electrical activity in nerves to improve organ function.', 'contact_email': 'jgrethe@ncmir.ucsd.edu', 'contact_name': 'Jeffrey Grethe', 'dcc_url': 'https://sparc.science/', 'dcc_abbreviation': 'SPARC'}
```
Is the RID the DCC ID? If not, can I add something to the cfde-deriva query to properly link the DCC IDs into the return?
This is the code I'm using to pull back the favorite DCCs:
```
path = registry_builder.CFDE.favorite_dcc
path = path.link(registry_builder.CFDE.dcc)
path = path.filter(path.favorite_dcc.user_id == user_id)    
rows = path.entities().fetch(headers=pass_headers())
```

**Comment by jrchudy** [comment]
From our discussion in UX meeting today, it looks like the "id" returned in the row of data for each favorite is the unique identifier to map to the DCC.

**Comment by ACharbonneau** [comment]
Is this still needed?
