### ISSUE TITLE
dashboard pages drop catalogId query param during redirects?

### ISSUE THREAD

**Issue by karlcz** [nih-cfde/dashboard#106]
I think the dashboard.html / udashboard.html / pdashboard.html pages have internal logic to redirect amongst each other depending on the client's login status. When this is done, the optional `?catalogId=X` query parameter seems to be dropped from the browser location.  However, if I use a page w/o redirect, e.g. go directly to pdashboard.html while logged in, I think it works as expected.

This is problematic for release preview tasks by staff, as links to charts for an alternative catalog will silently change into charts to the current public release if they happen to view the page w/ unexpected login status.

**Comment by jrchudy** [comment]
After doing some investigating, it appears both the home page and the dashboard honor `?catalogId=X` being present in the url. When present, the plots are showing data based on that catalog. I don't recall a conversation where we wanted to continue support for this feature on those 2 pages.

> pages have internal logic to redirect amongst each other depending on the client's login status.
I'm not sure where these links are. We should decide whether support for a `?catalogId=X` parameter should be supported on all static pages (home, dashboard, and dcc_review) or ONLY the dcc_review page.

**Comment by jrchudy** [comment]
From doing more investigation and our discussion in the UX meeting this morning, it seems that the case that the "catalogId" parameter is dropped is happening when it is present for the "udashboard" (no login session) and the user logs in to see the "pdashboard".

This doesn't appear to be the case on the homepage or dcc_review page after logging in.

**Comment by ACharbonneau** [comment]
is this still needed?

**Comment by karlcz** [comment]
I think it is a nice-to-have and would be beneficial for some internal 
testing purposes, but is not crucial for the public release UX.

**Comment by mschor** [comment]
I made this change during this April 2022 Q4-B cycle; but did not move this ticket status. However, clicking on the nav bar would also need to be changed to honor the catalog_id param. For example, when viewing: https://app-staging.nih-cfde.org/dcc_review.html?catalogId=258, if you want to navigate to one of the mentioned pages you have to click on the NavBar -> My Dashboard. That page will take you to dashboard.html which will then redirect to the auth or un-auth pages; however, dashboard.html needs to be given the catalogId param from the NavBar for this ticket to be completely resolved.

**Comment by jrchudy** [comment]
This was discussed further in the UX meeting today. We decided that supporting the url parameter (for testing purposes) from page to page navigation was not needed. Having the query parameter carry over form page to page is not a feature we intend to support and might cause a confusing UX flow for those that don't expect it to persist after viewing the dcc_review page.
