### ISSUE TITLE
Consistent use of DCC Full Names and abbreviations

### ISSUE THREAD

**Issue by jrchudy** [nih-cfde/dashboard#107]
Change the names of the DCCs in the plot on the static pages to use the full names like they do in deriva.
 - the labels on the x-axis each place the plot shows
 - on the personal dashboard, the box with DCC checkboxes to the right of the plot

**Comment by mschor** [comment]
Hi Amanda, I've started working this ticket and I'm trying to figure out which way I'm going towards working out consistency. Am I always displaying full names as Josh proposed at the top of the ticket or am I always using the abbreviation as you suggested for the favorites list? I'm testing with the full names and I have some concerns about real estate in the graphs and the personalized dashboard checkbox list.

**Comment by jrchudy** [comment]
In the UX meeting today, we suggested adding the abbreviation before the DCC name in the favorites list (`HuBMAP: The Human BioMolecular Atlas Program`). 

We also talked about adding a tooltip to the checkboxes to show the full name on hover, to find out this was already implemented. So maybe we need to have some hint that there are tooltips available on the checkbox labels?

The main concern with having the DCC full names everywhere is the length of some of the names. Some DCC names won't fit nicely in the checkbox panel or with 9+ DCCs showing their full name along the x axis of the plots.

**Comment by ACharbonneau** [comment]
I like:

> We also talked about adding a tooltip to the checkboxes to show the full name on hover, to find out this was already implemented. So maybe we need to have some hint that there are tooltips available on the checkbox labels?

the best. You're right that some of the names are super long and printing them is hard. If we can't do that, could we do 

>(HuBMAP: The Human BioMolecular Atlas Program). 

and have them trail off when needed? like `HuBMAP: The Human Bi...`

**Comment by ACharbonneau** [comment]
For the plots, if the DCC is on an axis, then it should show up in the hover over for the plot bar, and it doesn't need it's own hover over for just the axis. I'm assuming we can make the hoverover any size we want, so those should be the abbreviation plus name I think (HuBMAP: The Human BioMolecular Atlas Program)

**Comment by jrchudy** [comment]
Information icons added next to the legend on the personal dashboard page to help show there is a tooltip available on hover. On hover of the plots, the tooltip box that shows will show `"<DCC abbreviation>:<DCC name>".

Note, there is no space between the `:` and the name.
