### ISSUE TITLE
Timestamp truncation on personal dashboard

### ISSUE THREAD

**Issue by jrchudy** [nih-cfde/dashboard#109]
The time in the Creation Date column for the 3rd row (3 Data Types) appears to be truncated:
![image](https://user-images.githubusercontent.com/2932600/138507891-e440f830-018b-41fb-9fd2-f28c20e7d2b9.png)

This is the server returned row of data for that entry:
```
creation_ts: "2021-10-19T22:05:48.567473+00:00"
description: "This is the description that shows in the tooltip"
last_execution_ts: "2021-10-22T17:56:14.814626+00:00"
name: "3 Data Types"
query: "/chaise/recordset/#1/CFDE:collection/*::facets::N4IghgdgJiBcDaoDGALA9gSyQUwM53hCjABcxYAmABgBYaQAaI086mgDkebMoE4A2TgF0muNAFcATjgDW2AJ5wQAZQD6xMqpLyADti7YIJDNrglJ47EwC2YSTKhoA7hFUQw1-bBAARFgAIAFV19UQlpbHU0WwwIOFBcVGxbJQBhADEfAFEuMgAjABsvbjAtEK4kNALxazjvDBgAX0ahRqA?savedQueryRid=199E"
table_name: "collection"
```

Looks like the function to format the value uses `Date.getMinutes()` which returns the number of minutes.

**Comment by ACharbonneau** [comment]
Didn't this get fixed?
