### ISSUE TITLE
Limit total number of displayed X values

### ISSUE THREAD

**Issue by jrchudy** [nih-cfde/dashboard#110]
For the homepage plot, by default we are showing the Data Type along the X axis. This is an improvement from before where we only showed the first X options, but now we have noise at the end of the x axis in the plot where there is seemingly no data.

![image](https://user-images.githubusercontent.com/2932600/138536682-a8948e36-5239-43a1-8790-2e125165d47c.png)

We discussed this in standup and a few different solutions were suggested:
 - hard cut off at 10 options? 15 options?
   - could hide important information that some other configurations show if there's a hard cut off
 - hide an x axis option when its data sums to 5 or less?
   - might be too small to capture data that is in the 10s or 100s but the total set is in the millions
 - hide an x axis option if the data sums to `0.1%` of the largest brick? or `0.01%`?
 
Log vs non-log display also came up in this discussion to help the plot make some more sense in these cases where there seems to be no data. Related issue #71

**Comment by ACharbonneau** [comment]
I officially like the scroll better than cutting off the data. I think we just need to do any stuff that @mschor didn't get to for making it respond to size changes and whatnot
