### ISSUE TITLE
Personalized dashboard should get features from general dashboard

### ISSUE THREAD

**Issue by ACharbonneau** [nih-cfde/dashboard#114]
This is not a blocker for Q2 release

Currently the general dashboard actually has more plotting available than the personalized one, and there is not really a way to access the pie charts and whatnot once you've logged in. So registered users are actually losing features. We should add the plot carousel and other plots to the personalized dashboard.t

**Comment by mschor** [comment]
Hi, @ACharbonneau, would you mind suggesting what this would look like? Either a mockup or detailed description would be helpful. If I had to guess at it, I would think we want 2 thumbnail options: a bar graph and a donut chart. I'm assuming we'll want the donut chart to have the new DCC toggling ability as well. Is that right?

**Comment by jrchudy** [comment]
We talked briefly about how we could combine the udashbaord and pdashboard pages in the UX meeting today. One suggestion was to include the carousel content after the plots\ as a set of "predefined" filter criteria to apply to the plot to see some "interesting data".

We have to consider how to show the pie chart view too. Should it replace the bar graph the same way it does on the udashboard? Do the selected DCC's make sense for pie charts as well?

**Comment by mschor** [comment]
I added the donut charts to the personalized dashboard page. We reviewed what I had done before the winter break. Amanda thought it looked acceptable for the Q3 release.
