### ISSUE TITLE
Homepage and Dashboard plots use new data dimensions

### ISSUE THREAD

**Issue by jrchudy** [nih-cfde/dashboard#116]
The new dimensions added in quarter 2 need to be included in the dimensions for the plots. Dimensions added in quarter 2 include:
 - [x] sex
 - [x] race
 - [x] ethnicity
 - [x] compound
 
 The Portal c2m2 storage extension changes fo quarter 2 can be found in [issue #243](https://github.com/nih-cfde/cfde-deriva/issues/243) in the cfde-deriva repo.
 
Documentation for portal model extension:
https://docs.google.com/presentation/d/1nP04L076Lfk4SzC9fZYVnERLMSFZwFCn2nf8AgVQl7Q

**Comment by mschor** [comment]
I've added these 4 dimensions to the plot; however, 'compound' wasn't originally thought to be needed on this ticket so I had not originally asked Karl to add it to the legacy L1 stats in the cfde-deriva project. That dimension will not work until it's added there. I believe this is the relevant ticket: https://github.com/nih-cfde/cfde-deriva/issues/290

**Comment by jrchudy** [comment]
I can see the new dimensions available in the plot on the homepage, general dashboard page, and dcc_review page for both "x-axis" and "group by" dropdowns. 

The x-axis dropdown on the personal dashboard page does not include the compound option.

**Comment by mschor** [comment]
After discussion at Friday's UI meeting, we decided to Karl would not be adding compound to the legacy level1 stats queries so I have pulled compound as an option from all of the plots.
