### ISSUE TITLE
All widgets can be pointed at a new data release with no UI development required- data driven plots

### ISSUE THREAD

**Issue by ACharbonneau** [nih-cfde/dashboard#12]
@ACharbonneau commented on [Fri Nov 06 2020](https://github.com/nih-cfde/planning-docs/issues/83)

**Comment by jrchudy** [comment]
@jonathancrabtree @ACharbonneau I'm not sure I fully understand the intention of this issue. It seems like the work for it has been completed based on jonathan's comment above that was part of a commit message.

**Comment by ACharbonneau** [comment]
I think this is another one where I was writing issues as people requested during a meeting rather than me actually knowing what it meant :)

**Comment by jonathancrabtree** [comment]
@jrchudy, yes, thanks for closing this one. I'm not sure why I didn't do so in the commit, and it was perhaps only to note that the widgets and UI are still definitely schema-dependent but they should now be data-independent.
