### ISSUE TITLE
Update Portal Homepage to show new IDG data better

### ISSUE THREAD

**Issue by ACharbonneau** [nih-cfde/dashboard#122]
Add new icons to “Start your search” for new vocabulary terms “Disease”, “Gene”, and “Compound”.

**Comment by RLC-DCPPC** [comment]
disease - a stethoscope, virus model, gene: DNA helix, compound: 2d chemical model

**Comment by mschor** [comment]
Some icons I've found that might be decent candidates for these:
https://fontawesome.com/icons/virus?s=solid
https://fontawesome.com/icons/dna?s=solid
https://fontawesome.com/icons/pills?s=solid
https://fontawesome.com/icons/atom-simple?s=solid
https://fontawesome.com/icons/prescription-bottle?s=solid

**Comment by jrchudy** [comment]
I looked through the code in dashboard and the UI bit for this seems simple enough, but the changes to dashboard-api are a bit more complicated to understand. I wasn't able to make any progress on this issue. 

Let's wait until next week when Mike is back to finalize this issue.

**Comment by RLC-DCPPC** [comment]
@mschor, please look at this when you are back next week so we can resolve for Q4 (or push it out).
