### ISSUE TITLE
FAIR metrics display on DCC review page

### ISSUE THREAD

**Issue by jrchudy** [nih-cfde/dashboard#123]
We want to add another graphical display to the dcc_review page to show the percentages of compliance with each FAIR metric. Mike Schor has some mockups that this display will be based around.

The discussed requirements include:
 - The chart itself should be a bar chart
   - bars go from 0 - 100%
   - display bars horizontally
 - Show 2 graphs next to each other instead of having a long scroll bar
   - for small screens, 2nd chart goes below the first
     - is it possible to swap display of 1 vs 2 charts based on screen size?
 - Toggle button to swap between graph and table views
 - Hover over bar to get data from “comment” column (the ratio xxx/xxx)
 - Shorter more descriptive names for each bar

The data for this chart is in an appyter app (_fill in link.._). The appyter code is a python script that used the names that Amanda passed along with the data.  We want to ingest this data and store it somewhere (https://github.com/nih-cfde/cfde-deriva/issues/310) to be used by the graph/table on the review page. 

Information about the data:
 - Values are in the range of 0 to 1
   - these values represent percentages
 - Names should be shortened
 - each row needs a useful identifier as part of the ingest
 - "Comment” tries to show how many total are in compliance or not (more info than a percentage)
   - maybe we want to take the ratios in the comment column and store them some other way and leave the comment column for just comments?
 - “Problematic terms“ column in not important
 - “Principle” column is not important

**Comment by mschor** [comment]
Hi @karlcz, would you mind posting some instructions to this ticket regarding the steps I would need to take to pull the FAIR metrics from cfde-deriva? Thanks!

**Comment by karlcz** [comment]
See the new `metrics.get_datapackage_measurements(registry_catalog, submission_id)` utility function in cfde-deriva... 

```
def get_datapackage_measurements(registry_catalog, submission_id):
    """Return a sorted list of all measurement data for a given datapackage.

    Result is a list of dict-like measurements with fields:
    - datapackage: UUID-like submission id
    - metric: CURI-like metric concept id
    - metric_rank: sort ordinal configured for concept in registry
    - name: human readable metric concept name
    - description: human readable concept explanation
    - value: floating-point measurement value
    - numerator: numerator for ratio-based values
    - denominator: denominator for ratio-based values
    - comment: human readable augmentive text for value

    Results are sorted by:
    - ascending metric_rank as primary sort key
    - ascending name as secondary sort key to break ties
    """
...
```

However, I realize now that this is probably missing an optional `headers` parameter like we do in dashboard queries to allow you to use different client credentials on each request.  I'll try to add that soon.

**Comment by ACharbonneau** [comment]
This looks good in staging so far, but I have two requests

1. Could we give the names a hoverover with the descriptions
2. for the 'see raw data' link, can it go to the actual datapackage raw and not just the list? Example: for RID 9A1G I'd like it to go to https://app-staging.nih-cfde.org/chaise/record/#registry/CFDE:datapackage/RID=9A1G
