### ISSUE TITLE
Q4 favorite widgets for personal dashboard

### ISSUE THREAD

**Issue by jrchudy** [nih-cfde/dashboard#124]
We are adding new favorites that need to have corresponding widgets on the personal dashboard. The 3 favorites being added are "Analysis Type" and "Phenotype" and "Protein".

Related issue in cfde-deriva:
https://github.com/nih-cfde/cfde-deriva/issues/284

**Comment by mschor** [comment]
I've added the code for this to the dashboard-api project. There's a small amount of code to be added to the dashboard project as well. The related issue that Josh linked in the initial description is a dependency for this work.

**Comment by mschor** [comment]
I've also updated the dashboard project, however, I am unable to star any of these as favorites in app-dev at this time so I cannot fully test this.

**Comment by jrchudy** [comment]
I can confirm from testing on staging that Analysis type and Phenotype are working. Protein won't allow me to add favorites in the facet UI, so I can't confirm whether this is working or not.
