### ISSUE TITLE
Dashboard interactive chart resizing

### ISSUE THREAD

**Issue by ACharbonneau** [nih-cfde/dashboard#126]
The dashboard chart is acting extremely weird. It seems like HMP, procca, and SPARC all make the chart get smaller, but only if they are selected with specific other DCCs. I don't know how to best explain it so I made a video

https://user-images.githubusercontent.com/1719360/160696827-7ca98fe3-a481-47bc-b33b-a7c2b440ecbb.mov

**Comment by mschor** [comment]
That is very weird, indeed. Good find; and thanks for the video explanation. I just tried this in production and it looks like it's broken there as well.

**Comment by mschor** [comment]
Fixed and committed to repo. I'll update this ticket once it's available for testing.
