### ISSUE TITLE
Favorites box auto enlarge

### ISSUE THREAD

**Issue by ACharbonneau** [nih-cfde/dashboard#129]
I gave myself an absurdly large number of favorite anatomys, and the box actually nicely expands to fit them, so it's fine. But I'm wondering if at some point it would be nice if it could columnize for very long sets rather than just get longer, since theres so much whitespace on the right.

![image](https://user-images.githubusercontent.com/1719360/160702901-4076c94b-1158-4225-a33c-5680355e6293.png)

**Comment by jrchudy** [comment]
We decided that the implementation for this should include paging to handle long lists of favorites with 10 favorites shown on each page. 

Having multiple columns was suggested but that opens up the issue with long names of favorites and having to manage that at different zoom levels. If a user is zoomed in very far, multiple columns might not be possible.

**Comment by jonathancrabtree** [comment]
The Saved Searches box on the personalized dashboard already implements pagination of this sort, so some reuse should be possible here:

![Screen Shot 2022-06-06 at 8 58 03 PM](https://user-images.githubusercontent.com/5394345/172273492-17d226b4-1d7a-4cae-9aee-93aef5cb928d.png)

**Comment by raynamharris** [comment]
Update/clarification, this is enabled on the main favorites page but not the tabs. See https://github.com/nih-cfde/cfde-deriva/issues/363#issuecomment-1176726657

![177640893-a3fdf123-9873-4122-9415-3df8c28857d8](https://user-images.githubusercontent.com/7544197/177697069-8470e380-2918-40b5-983a-96bd4a8295e9.png)

![177640862-f86278a1-ef29-4aa3-a490-e5ec6cea9203](https://user-images.githubusercontent.com/7544197/177697064-bb8722cd-22b5-442c-8bde-b12a57594cb5.png)

**Comment by jonathancrabtree** [comment]
Deployed on app-dev for testing e.g., Anatomy:

![Screen Shot 2022-07-13 at 2 26 31 PM](https://user-images.githubusercontent.com/5394345/178818121-4150c77b-e1d7-4d48-b454-803c94dbbaf9.png)

Assay:

![Screen Shot 2022-07-13 at 2 26 50 PM](https://user-images.githubusercontent.com/5394345/178818141-eb20aede-439d-4b3d-a520-a712ffbaafc0.png)

Compound:

![Screen Shot 2022-07-13 at 3 41 39 PM](https://user-images.githubusercontent.com/5394345/178818174-034afda6-7f27-4bc7-8a5c-a1061e74a99f.png)

Note that:

- Some of these entities have abbreviation, name, and description (plus id and url) that we could potentially display in multiple columns.
- Currently the abbreviation (if present) and name are shown in the table and the name and description (if present) in the hovertext.
- There are compounds that take up most of the horizontal space even with the single column layout.
- It does not appear to be possible to favorite Proteins (should the tab be removed if so?)

**Comment by jrchudy** [comment]
This looks really nice now. Leaving open so it can be tested after code freeze.
