### ISSUE TITLE
The connection between the summary info of submissions and the high level error info needs to be a globus automate interaction

### ISSUE THREAD

**Issue by ACharbonneau** [nih-cfde/dashboard#13]

**Comment by jrchudy** [comment]
@ACharbonneau I'm not sure what this issue is about. Could you provide more information or move it to the appropriate repository?

**Comment by ACharbonneau** [comment]
I don't really know what this means, I suspect I was typing these word for word for people during a meeting and then it got forgotten. I think it's probably something @lliming or @rpwagner said about how to make submission error messages appear in the registry? But if neither of them remember this and/or it's no longer relevant we can just close it.

**Comment by rpwagner** [comment]
I don't recall what this referred to specifically. And with the work Nick and Karl are doing now whatever requirement drove this is likely being addressed.
