### ISSUE TITLE
New icons (disease, gene, and compound) stack vertically on homepage

### ISSUE THREAD

**Issue by jessicalumian** [nih-cfde/dashboard#133]
The disease, gene, and compound icons are stacking vertically on my laptop screen. I didn't see this issue before on my desktop computer, so I'm guessing it has to do with screen size. However, I did all testing  on this laptop, and never saw the icons look like this, so maybe not.

<img width="1721" alt="Screen Shot 2022-05-03 at 8 53 13 AM" src="https://user-images.githubusercontent.com/9140844/166490554-34a52ef3-fd40-46ba-85d5-b74c74c7a27d.png">

**Comment by lliming** [comment]
FWIW, I can't reproduce this under any conditions I've tried (browser zoom scaling, window sizing, etc.).  I'm using an up-to-date Firefox browser on an up-to-date Mac.  I wonder if it has to do with browser caching? Have you tried clearing your browser cache?  If that fixes it, then we should investigate to figure out which page element is getting cached and not refreshed. Maybe a stylesheet?
<img width="1424" alt="Screen Shot 2022-05-03 at 10 12 27 AM" src="https://user-images.githubusercontent.com/19350820/166493234-3f74d17a-ecb6-48a3-959c-0858062504ec.png">

**Comment by jessicalumian** [comment]
Clearing my browser cache resolved this issue! I'm using an up-to-date Mac and up-to-date firefox. I've been loading the portal a lot over the past few days, but this is the first time I opened it on this mac since the update. I think browser cache was the issue here.

<img width="1713" alt="Screen Shot 2022-05-03 at 10 22 19 AM" src="https://user-images.githubusercontent.com/9140844/166506198-c21c74c8-69a3-4e49-9a2a-fd685b95452b.png">
