### ISSUE TITLE
Missing Metabolomics and KF from "Common Fund Program" filter in Collections

### ISSUE THREAD

**Issue by jessicalumian** [nih-cfde/dashboard#134]
I navigated to Collections, then Common Fund Program. I see all the DCCs except for Metabolomics and KF. Is there a reason these two groups are not available, or is this a bug that can be fixed?

![Capture1](https://user-images.githubusercontent.com/9140844/166759480-4cf441d2-21a8-4292-add3-cd3d64d44150.PNG)

![Capture2](https://user-images.githubusercontent.com/9140844/166759790-f520b255-5108-4497-b2aa-dd223474efbf.PNG)

**Comment by lliming** [comment]
Hi Jessica. What this means is that Kids First and Metabolomics didn't define any collections in their submissions. (When you're browsing collections, the "Common Fund Program" search facet will only list programs that have collections defined.)

To sanity check that, I reviewed Kids First's most recent approved submission in the submission registry, and it indeed looks like there were no collections in that submission. (I looked at the new metadata connectivity section and all the collection metrics are 0 for that submission. Also, the "KFDRC Data Review" table shows no collection stats.)

In at least one other area of the interface, I've seen an option available to reveal search facets that have 0 records, but I don't see it here. We'd need someone from the Deriva team (maybe @karlcz ) to explain when that option is and isn't available.

**Comment by karlcz** [comment]
Facet search controls always limit themselves to values connected to the
current data context.  In other words, when you first start in the 
recordset app the facets will only show values connected to at least one 
of the records in the table.

As you start to set search criteria in a facet, this narrows the context 
and even fewer options will appear in _other_ facets depending on the 
metadata connectivity of the narrowed search results. This is an 
important part of faceted search as it communicates how different 
concepts are correlated and focuses the user on metadata that is still 
available to further differentiate among the records in the current search.

However, a facet does not restrict _its own_ search context, as that 
could make it impossible to widen a search. For example: search in 
biosamples, choose one anatomy term, then choose a second to find 
records matching either term. If the first selection were part of the 
context, then no other anatomy terms would be available anymore to 
broaden the criteria to multiple anatomy terms!

There is a "show more" button to open a modal window that may allow 
paging through more connected terms than are visible in the limited 
"first page" of options in the facet control itself. But this modal will 
still only show the terms that are connected to the current search 
context. It won't show disconnected choices.

You may be thinking of a feature in the record app to "show empty 
sections".  This app focuses on a single "main record" at the top of the 
page and then shows other related records as sub-sections with nested 
tables.  There are multiple such sub-sections, one for each different 
relationship we've elected to show on these pages.  For example, a 
collection record can show sections for the files, biosamples, and 
subjects contained in the collection.  When there are zero related 
records available by one relationship in C2M2, that section is "empty" 
and hidden by default, to make the rendered page more clearly emphasize 
those relationships.

**Comment by jrchudy** [comment]
Issue moved to [nih-cfde/cfde-deriva #350](https://github.com/nih-cfde/cfde-deriva/issues/350) via [**ZenHub**](https://www.zenhub.com/)
