### ISSUE TITLE
Create separate repository for portal guide documentation

### ISSUE THREAD

**Issue by ACharbonneau** [nih-cfde/dashboard#14]
@ACharbonneau commented on [Mon Nov 09 2020](https://github.com/nih-cfde/planning-docs/issues/85)

From comment on April 2nd (edited Sept 17, 2021):
> From the UX meeting this morning, Amanda stated that having the portal guide documentation as it's own repository would allow for "Portal and Dashboard User Guide" to be it's own top level option in the navigation bar here:
https://docs.nih-cfde.org/en/latest/about/portalguide/

> We should move the content for that page into a new repository.

**Comment by ACharbonneau** [comment]
when the @nih-cfde/ui team incorporates this, please let @nih-cfde/training know so we can take it out of the documentation site

**Comment by ACharbonneau** [comment]
@fridayek Is this still a real issue? I'm not sure if the docs are really moving directly to the portal, or getting their own repo to be added to the documentation site?

**Comment by fridayek** [comment]
I'm not sure what the plan is either since I don't know the pros and cons of each option. I'm fine closing this ticket until I/we decide on how to proceed.

**Comment by ACharbonneau** [comment]
I'm changing the issue title and moving this to Epic 2 technical debt. It is actually Epic 1 technical debt, but it does't seem to have been resolved and that epic is closed out. 

Currently the portal documentation lives as a single page here: https://github.com/nih-cfde/published-documentation/blob/stable/docs/about/portalguide.md 

and is rendered as part of the "about" section of the documentation website here: https://docs.nih-cfde.org/en/latest/about/portalguide/ 

It was shoehorned into this repo at the last minute, because the docs needed to be part of the October release, but weren't done until a day or two before, and there wasn't place provisioned for them in the portal. So, we decided to put it in a temp location in an unrelated website and link to it, so currently the portal links out to the rendered version in my site. Associated issue was https://github.com/nih-cfde/cfde-deriva/issues/22

The plan, as I understood it in November, was that the docs team would work with the deriva team to figure out where these docs would live, and what format they need to be. The options as I have heard them are:

1. It stays in the about section of the docs site, as an increasingly large page
2. It moves to be a part of the portal, so it isn't a link out
3. It gets its own repo and I pull it into the docs site as it's own section, like the c2m2, cfde-submit, etc

1 is completely untenable in my opinion. It's completely unfindable, and weird to have it under the about pages. 

1 & 3 both make the user go to a separate website in order to learn how to use the portal, which is generally considered to be a poor user experience.

2 I have no ability to say how easy or difficult this is, but it would presumably provide the nicest user experience

@lliming maybe this should be a discussion in a Tuesday call? I feel like I've somehow gotten into the middle of a decision process between two teams I'm not even on.

**Comment by fridayek** [comment]
Thank you for the details, @ACharbonneau. This helps me a great deal. I agree that it would be best to make it part of the portal, but I would need more information from the Deriva team (I think) to determine the feasibility and best way to maintain it.

**Comment by RLC-DCPPC** [comment]
> Thank you for the details, @ACharbonneau. This helps me a great deal. I agree that it would be best to make it part of the portal, but I would need more information from the Deriva team (I think) to determine the feasibility and best way to maintain it.

So perhaps, @jrchudy or @karlcz have thoughts on this?

**Comment by jrchudy** [comment]
Having the docs as part of the portal isn't a feature that deriva supports. We could include them as another page alongside the dashboard code with the deriva navbar so it appears to stay internal alongside the portal.

I think including it with the other documentation is also important, whether that means moving all documentation to somewhere alongside the portal or putting the portal guide documentation with the others docs.
> It gets its own repo and I pull it into the docs site as it's own section, like the c2m2, cfde-submit, etc

We will discuss this on Friday at the UX meeting.

**Comment by jrchudy** [comment]
From UX meeting this morning, Amanda stated that having the portal guide documentation as it's own repository would allow for "Portal and Dashboard User Guide" to be it's own top level option in the navigation bar here:
https://docs.nih-cfde.org/en/latest/about/portalguide/
