### ISSUE TITLE
Saved search box on personal dashboard should sort by creation time by default

### ISSUE THREAD

**Issue by jrchudy** [nih-cfde/dashboard#140]
Currently the Saved Searches box on the Personal dashboard is sorted by "Search Name" by default. This should be changed to sort by Creation Time by default instead.

A question about this was raised during testing:
https://github.com/nih-cfde/cfde-deriva/issues/363#issuecomment-1176726657

**Comment by jonathancrabtree** [comment]
Before:

![Screen Shot 2022-07-11 at 7 45 55 PM](https://user-images.githubusercontent.com/5394345/178398587-0b27012a-35e2-4cbe-8a22-f21846f391c2.png)

After:

![Screen Shot 2022-07-11 at 10 54 48 PM](https://user-images.githubusercontent.com/5394345/178398612-9a48c5ad-81ed-4d89-8b65-3cf9ddebcd52.png)

**Comment by jonathancrabtree** [comment]
Ready for testing on app-dev

**Comment by jrchudy** [comment]
I verified this is the behavior on app-dev.
