### ISSUE TITLE
Download button broken for pie charts on pdashboard.html and udashboard.html

### ISSUE THREAD

**Issue by jonathancrabtree** [nih-cfde/dashboard#147]
Confirmed on both production and current app-dev. The stacked bar graph download button on the same page works ok.

![Screen Shot 2023-02-14 at 9 46 09 PM](https://user-images.githubusercontent.com/5394345/218914242-317d4574-a423-4796-a30d-30bffef77d05.png)

**Comment by jonathancrabtree** [comment]
udashboard.html shows the same error for the download button on both of the pie charts there.

**Comment by jonathancrabtree** [comment]
It's not clear that this was ever functional; it looks like hooking up the download buttons may have been lost in one of the handoffs. However, for any image download to be useful it would have to also include the color key, which is not currently the default, at least for the (formerly stacked) bar graphs.

**Comment by mgiglio99** [comment]
This sounds great - thanks Jonathan.

**Comment by jonathancrabtree** [comment]
Ready for testing on app-dev.

**Comment by jonathancrabtree** [comment]
Tested in production on both udashboard and pdashboard. Closing.
