### ISSUE TITLE
PortalGuide documentation needs information about review page

### ISSUE THREAD

**Issue by ACharbonneau** [nih-cfde/dashboard#15]
Current documentation doesn't include review page. Docs will also need to be formatted however the @nih-cfde/ui team needs in order for the docs to move to being hosted directly in the portal #14

**Comment by ACharbonneau** [comment]
Sorry. Specifically, it doesn't include information about accessing the Review Catalog. 
It would also be good to update the wording "The Data Review page displays a personalized dashboard for you to verify the data currently available for your DCC." is not quite right. This page doesn't show the currently available data at all, it shows a recent data submission that *has not been incorporated into the main catalog yet*, so that a data admin can decide whether it is right, and should be incorporated into the portal.

**Comment by jrchudy** [comment]
@ACharbonneau does this issue belong in this repository? Maybe it should be in the published-documentation repository?

I'm afraid it might have been lost or forgotten in here..

**Comment by ACharbonneau** [comment]
there isn't really a repo for it, so here is fine. Just need to assign it to @fridayek

**Comment by fridayek** [comment]
I updated the CFDE User Guide with the Data Review pages. I have a lot of details about the "how" to do something, but less about the "why," so please review and let me know if there are any details I should add.
https://docs.google.com/document/d/1S5ll51sKuFuV3uzCQrCZM_y23nqevP55x42guhAsuOI/edit# 

Also, I was told to not take screenshots from staging, so I will need to update those at some point.

**Comment by fridayek** [comment]
@ACharbonneau Can you help me add more information about how the approval process will be handled? If you have any existing documentation, I can incorporate that. Or I'm available to meet if you'd rather discuss. Perhaps @karlcz can show me how it will work in the portal?

**Comment by ACharbonneau** [comment]
I have use cases written about how it works at a high level, but they're in the process of being updated so some of the details are wrong. But the order would be roughly 4, 8, 9, 10 here https://use-cases.nih-cfde.org/uc-0004/

It would probably be easier if you could give me the questions you have or just meet with Karl and/or me to talk through it.

**Comment by RLC-DCPPC** [comment]
Hi @fridayek. How are we doing on this? Do you need any assistance?

**Comment by fridayek** [comment]
I met with Karl and Amanda a few weeks ago to discuss the approval process, and I updated the User Guide with this information. This ticket can be closed.
