### ISSUE TITLE
Catalog review page should take a DERIVA catalog id as a parameter.

### ISSUE THREAD

**Issue by jonathancrabtree** [nih-cfde/dashboard#17]
The catalog review page (currently dcc_review.html) should accept a DERIVA catalog id as a parameter and display information only for the specified catalog.

**Comment by jonathancrabtree** [comment]
This work is complete, although there's an issue with parameterizing the DCC review page, which is that the page is designed to display a DERIVA catalog that contains data from a _single_ DCC (i.e., the data uploaded by that DCC prior to approval/incorporation into a multi-DCC release catalog.) Since any catalog id might be passed to the page, the question is what to do if it's given a catalog that contains data from multiple DCCs. For now it's simply using a JavaScript alert() to let the end user know there's a problem, as seen here:

![Screen Shot 2020-12-16 at 4 27 33 PM](https://user-images.githubusercontent.com/5394345/102415276-e6e7f300-3fc5-11eb-82a6-d99a7480e356.png)

If the catalog id is for a catalog that contains data from only one DCC then everything behaves as before. Here for example, is dcc_review.html?catalogid=6 from app-dev:

![Screen Shot 2020-12-16 at 4 27 09 PM](https://user-images.githubusercontent.com/5394345/102415368-0bdc6600-3fc6-11eb-9ecc-fbc2ce85b03e.png)

In future we might consider displaying a more visually-pleasing error message or generalizing the page to the multi-DCC case (although that may entail dashboard-api changes, depending on the exact spec.)

**Comment by jrchudy** [comment]
This looks like another issue that we can close. The concerns regarding error handling seem to addressed in the current implementation and in issue #48 .

@jonathancrabtree please update this with any extra information you think is missing.
