### ISSUE TITLE
Home Page inconsistencies

### ISSUE THREAD

**Issue by jrchudy** [nih-cfde/dashboard#18]
For the home page, not much was out of sync. The major changes missing are enumerated below:
 - [ ] Timestamp in the top right corner of summary view missing.
 - [x] Download button is still the grey icon style instead of the blue button with text
 - [x] 4 row chart in upper right corner not present with summary info about data sets

Image of highlighted missing pieces from wireframe:
![image](https://user-images.githubusercontent.com/2932600/100652511-e2e87f80-32fb-11eb-8a33-40311aa28295.png)

**Comment by jonathancrabtree** [comment]
Added missing 4-row chart. Note that there's some redundancy here insofar as the links for subjects, biosamples, and files (in newly-added 4-row chart) are identical to those for subject, biosample, and file under the "View Data By" section on the left side of the page:

![Screen Shot 2020-12-07 at 9 48 27 AM](https://user-images.githubusercontent.com/5394345/101365200-817f5e00-3871-11eb-8712-35e4b8d09cc1.png)

**Comment by jonathancrabtree** [comment]
Added timestamp:

![Screen Shot 2020-12-07 at 10 10 06 AM](https://user-images.githubusercontent.com/5394345/101367757-70841c00-3874-11eb-9df6-d2e697586cc4.png)
