### ISSUE TITLE
Dashboard inconsistencies

### ISSUE THREAD

**Issue by jrchudy** [nih-cfde/dashboard#19]
For the dashboard page, some overall changes were asked of us. It was noted that showing all graphs on page load may be confusing since it "hides" some of the data. 

Instead we want a default graph to show with a select area that enumerates each graph available so users can see what is there at a glance and choose what they want to see. If they expand all, all graphs should show like we did for the demo in June.

Content missing:
- [x] "Select Data view" box not present to show which dashboard graphs are available
  - Thumbnail images for each dashboard graph for the select box view
  - "Expand all" button to show all graphs at once
  - similar to the presentation we provided for June demo
- [x] Download button is still the grey icon style instead of the blue button with text
- [x] Timestamp in the top right corner of displayed graph missing

Image of highlighted missing pieces from wireframe:
![image](https://user-images.githubusercontent.com/2932600/100652611-07445c00-32fc-11eb-951c-21326296bd0c.png)

**Comment by jonathancrabtree** [comment]
Added "Select Data View" functionality. It's not exactly the same as the screenshot in terms of look and feel yet, but the basic functionality is there:

![Screen Shot 2020-12-08 at 9 41 38 AM](https://user-images.githubusercontent.com/5394345/101498055-a7703580-3939-11eb-867f-cf449ee6be09.png)

**Comment by jonathancrabtree** [comment]
Change CSS to more closely match the spec. Now the selected thumbnail is de-emphasized/grayed out:

![Screen Shot 2020-12-08 at 10 08 11 AM](https://user-images.githubusercontent.com/5394345/101501277-8c9fc000-393d-11eb-958b-5bf769e74a8c.png)

**Comment by jonathancrabtree** [comment]
Added 'last_updated' to charts (based on cached JSON for now, will use API directly for Epic 2):

![Screen Shot 2020-12-08 at 10 26 53 AM](https://user-images.githubusercontent.com/5394345/101503376-08027100-3940-11eb-88e2-fbb18753a35c.png)

**Comment by jonathancrabtree** [comment]
Closing, although note that the donut charts could probably be widened now that they won't always be on the same line (which would also help with the label runoff problem):

![Screen Shot 2020-12-08 at 10 41 50 AM](https://user-images.githubusercontent.com/5394345/101505155-09349d80-3942-11eb-9e07-23301d968bd4.png)

![Screen Shot 2020-12-08 at 10 42 44 AM](https://user-images.githubusercontent.com/5394345/101505234-21a4b800-3942-11eb-95eb-db3d0d9c33e7.png)
