### ISSUE TITLE
DCC Review inconsistencies

### ISSUE THREAD

**Issue by jrchudy** [nih-cfde/dashboard#20]
- [x] Numbers were not linked in Data Total or Data breakdown 
- [x] Scroll bar in Data Review table
  - this is noted in the pdf and shown as something in the wireframe
  - make sure if the content to fill that space is dynamic, that a scroll bar is present
- [x] "Data Review" box (left side) and "Data Snapshot" box (top right side) should have the same height

Image of highlighted missing pieces from wireframe:
![image](https://user-images.githubusercontent.com/2932600/100652657-16c3a500-32fc-11eb-94a4-b7ca0c41e174.png)

**Comment by jonathancrabtree** [comment]
Enabled vertical scrolling on Data Review panel, matched height with Data Snapshot panel. Note that the *appearance* of a scrollbar in the former is very much platform dependent. In Mac OS X Chrome, for example, the scrollbar will appear only when the user attempts to scroll the panel/table. In Linux Chrome it is always visible, as shown here:

![review-page-scrollbar](https://user-images.githubusercontent.com/5394345/101175468-3405b580-3613-11eb-9d16-e209609bd28e.png)

**Comment by jonathancrabtree** [comment]
The links have been added, but are hard-coded to reference app-dev.nih-cfde.org/catalog id 6. This is a temporary solution to satisfy the short-term IG review requirement. Tested that all links work and display the relevant Chaise page and that the number of objects displayed matches the number in the Data Review table:

![Screen Shot 2020-12-05 at 11 47 25 AM](https://user-images.githubusercontent.com/5394345/101258368-0c384f80-36f0-11eb-85d1-9532babac3b9.png)
