### ISSUE TITLE
Layout problem.

### ISSUE THREAD

**Issue by jonathancrabtree** [nih-cfde/dashboard#26]
Relatively minor layout problem in index.html and dcc_review.html. When the browser window is made too narrow the data preview box in the top right gets kicked down to the next line and obscured by other content.  "Normal" width window:

![Screen Shot 2020-12-07 at 9 43 47 AM](https://user-images.githubusercontent.com/5394345/101364668-d2428700-3870-11eb-9be2-7492a3020c4f.png)

Narrow window. Note data preview box from top right now hidden under "Data Review":

![Screen Shot 2020-12-07 at 9 44 00 AM](https://user-images.githubusercontent.com/5394345/101364709-dcfd1c00-3870-11eb-93ad-7c5ffdcc3268.png)

**Comment by jrchudy** [comment]
I don't recall the decision we made in the UX meeting when we discussed this, but looking at that incorrectly wrapping table (and the one on the left), they contain identical information. This might always be the case, which would render this incorrectly wrapping table pointless and redundant.

**Comment by jrchudy** [comment]
Found a comment from a few days ago referencing that we want to remove the table:
https://github.com/nih-cfde/cfde-deriva/issues/173#issuecomment-797754192

> Additionally, we're going to delete the top right box thing that looks like this ONLY FOR REVIEW PAGES. It stays on the homepage and anywhere else it exists

**Comment by jonathancrabtree** [comment]
#72 covers the task of removing the table. I'm closing this one as a "wontfix" since we're not actually fixing the layout.
