### ISSUE TITLE
Remove cached JSON files from data/ subdir.

### ISSUE THREAD

**Issue by jonathancrabtree** [nih-cfde/dashboard#37]
Depends on #25.

**Comment by jrchudy** [comment]
@jonathancrabtree I believe these changes have been completed and merged already. Could you verify this and close this issue if so?

**Comment by jrchudy** [comment]
The above is a history of my confusion and later understanding of this issue. Sounds like this issue was opened to "Remove the files once the API change was made". The API change was made, so we should be able to remove those files now.

If that's not the case, can you update this issue with why we still need them around.

**Comment by jonathancrabtree** [comment]
@jrchudy the problem here is that we're developing on a branch, so although I closed the issue in a commit message, GitHub won't actually close the issue until the branch is merged back onto master. At that point any commit message auto-closures will take effect. I'm going to leave the issue open but will check after tomorrow's merge and release that it is closed correctly. The files in question _have_ been removed, but only on the Epic 2 branch.

**Comment by jrchudy** [comment]
I didn't know you could "auto-close" issues with commit messages. I'll have to test this out some times.

**Comment by jonathancrabtree** [comment]
Just checking that this issue was closed by the merge, and it was. It's an interesting question, though, because my close commit occurred before you reopened the issue (I think.) But it appears what matters is when the commit makes it onto master, not when the commit originally occurred in the branch.
