### ISSUE TITLE
Assess/optimize page load times

### ISSUE THREAD

**Issue by jonathancrabtree** [nih-cfde/dashboard#38]
A separate issue to handle the task of assessing and improving the page load times after completing #25. Attention should be paid to worst-case behavior and the effect of the automatic deriva-py caching in the dashboard-api. It may be possible to combine certain requests, reduce the number of requests, or make better use of multiple concurrent requests. Page elements may need to be modified to show loading indicators.

**Comment by jonathancrabtree** [comment]
Note  that this relates to https://github.com/nih-cfde/cfde-deriva/issues/128 - any overly-slow cfde-deriva queries should be reported/addressed there.

**Comment by jrchudy** [comment]
@jonathancrabtree any updates for this task? 

I recall sometime near the middle to end of January (or early February) that changes were added to the dashboard API repository to help with this.
