### ISSUE TITLE
Epic 1 Inconsistencies Review

### ISSUE THREAD

**Issue by jrchudy** [nih-cfde/dashboard#40]
The list of tasks to clean up the UI to align with the wireframes from Epic 1 have been completed. Opening this issue to continue the process to review those changes and decide whether those issues have been properly completed.

Linking github "epic" with all attached sub tasks https://github.com/nih-cfde/dashboard/issues/22.

**Comment by ACharbonneau** [comment]
Since this is rolled into testing for epic 2, I've put the info in the overall testing issue https://github.com/nih-cfde/training-and-engagement/issues/326
