### ISSUE TITLE
Security Warning

### ISSUE THREAD

**Issue by ACharbonneau** [nih-cfde/dashboard#41]
Not sure if everyone gets these notifications, but there is a new security warning for axios https://github.com/nih-cfde/dashboard/security/dependabot/yarn.lock/axios/open

**Comment by victor73** [comment]
This is a dependency of browser-sync, which (currently) isn't used at runtime. So the severity isn't that critical in our case.

**Comment by victor73** [comment]
Link: https://github.com/BrowserSync/browser-sync/issues/1831

**Comment by victor73** [comment]
Forced newer version of axios.
