### ISSUE TITLE
Update banner above navbar

### ISSUE THREAD

**Issue by jrchudy** [nih-cfde/dashboard#42]
We would like to have different banner colors and text for each of dev, staging, and production for the banner that shows up above the navbar. Currently the banner is maroon with the text:
 >  "The data displayed on this page is not official and only for testing purposes."
 
 @ACharbonneau what should be the color for each of the 3 servers and what should be the text that we us? Should it be the same line of text but with the server name changed?

Another thought, should this only be a banner for dev and staging? Which means production could have no banner.

**Comment by ACharbonneau** [comment]
I think that in the future, production will have no banner, and it will just be a warning for dev and staging. For this exact moment though, I think we need to keep the "The data displayed on this page is not official and only for testing purposes." warning on production, as none of the DCCs have updated their data yet.

So for right now, how about:

- on production, message and color stays exactly the same
- on dev, message changes to "This is a development server! It is not official and only for development purposes." and we make it #447e71
- on staging we make it "This is a staging server! It is not official and only for testing purposes." and make it #7e4475

(I'm not married to these colors, I just picked two with about the same hue)

**Comment by jrchudy** [comment]
Removing from "technical debt in epic 1" epic since this had nothing to do with epic 1. This was a change asked about early in January to help differentiate each server (dev/staging/production) from each other at a glance without reading the url.

This got swept under the rug and will be resolved within the next week.

**Comment by jrchudy** [comment]
Closing this issue since https://github.com/nih-cfde/cfde-deriva/issues/163 was created in cfde-deriva with more recent text.
