### ISSUE TITLE
Remove timestamps from plots

### ISSUE THREAD

**Issue by ACharbonneau** [nih-cfde/dashboard#46]
We talked about this in the UI meeting. The dates are confusing and I don't think we can make them meaningful, lets just drop them.

- Remove for index.html, dashboard.html
- Leave for dcc_review.html 

If its easy, we might consider adding a hover over UI element to give more contextual metadata about the dates for each of the datasets in that plot

**Comment by jonathancrabtree** [comment]
Closing, as this looks OK to me on app-dev.

**Comment by jonathancrabtree** [comment]
Also removed timestamp from summary_graph.html, as mentioned in #30.
