### ISSUE TITLE
New widget type for favorites

### ISSUE THREAD

**Issue by jrchudy** [nih-cfde/dashboard#49]
As part of the personalized dashboard feature, we will need a new widget added to display lists of information. It's uncertain if this should be a bulleted list, a numbered list, or a display that more resembles a table.

Link to favorites widget design:
https://drive.google.com/file/d/1i2F5zgM65-Ksh1xrqcGd0S8sl-5uNvlX/view

**Comment by jrchudy** [comment]
The personalized dashboard will use this widget for listing the favorites that each user has saved. The widget will be a list of href links.

The following favorites should use this widget:
 - Favorite DCC
 - Favorite assay
 - Favorite anatomy

**Comment by jonathancrabtree** [comment]
@jrchudy I added this issue to Personalized Dashboard since #77 was already in there. Let me know if this isn't correct.
