### ISSUE TITLE
Favorite DCCs

### ISSUE THREAD

**Issue by jrchudy** [nih-cfde/dashboard#50]
Using the widget added in issue #49, a new widget needs to be added to the carousel to display a list of summary statistics and catalog update information about the user's favorite DCCs.

**Comment by karlcz** [comment]
The "Common Fund Program" facets in the catalog, which will use the `S_dcc` sourcekey and list entities from the `dcc` table, should use the `dcc.id` key column for the saved favorites.  This will be a stable key, much like the other vocabluary tables' `id` key.
