### ISSUE TITLE
History of Queries

### ISSUE THREAD

**Issue by jrchudy** [nih-cfde/dashboard#51]
Using the widget added in issue #77 , a new widget needs to be added to the carousel to display a list of previously searched queries. This is sort of like the CFDE Portal equivalent of the browser’s search history. The list will show the last N searches, where N has not been decided yet. Maybe a profile configuration option?

**Comment by karlcz** [comment]
I think this user story is either undefined or no longer scheduled for the 2021-Q1 deliverable.  In multiple phone calls, we discussed that the only persistence would be the saved queries populated by user action. There would be no automatic saving. Hence, this list is synonymous with the saved queries list!

**Comment by ACharbonneau** [comment]
I think this doesn't need to be a user feature, however I would like to be able to get a monthly? quarterly? Some time period readout of what searches people did if that's possible. For tracking/reporting. Absolutely can just be a csv or something that I parse

**Comment by jrchudy** [comment]
I think this issue can be marked as closed since we added the "Last Searched" column to the "My Dashboard" page.
![image](https://user-images.githubusercontent.com/2932600/132793468-bc57148c-1cbd-494c-84c5-f87d8b27b855.png)

@ACharbonneau should we address your last comment as part of this issue or move it to another one so this can be closed?
