### ISSUE TITLE
Saved queries

### ISSUE THREAD

**Issue by jrchudy** [nih-cfde/dashboard#52]
Using the widget added in issue #77 , a new widget needs to be added to the carousel to display a list of saved queries. This is sort of like the CFDE Portal equivalent of the browser’s bookmarks.

**Comment by karlcz** [comment]
The `saved_query` table in the registry will contain records with the columns:
- `user_id` : the authenticated user ID of the profile owner
- `schema_name` : should always be "CFDE" for this use case
- `table_name` : the C2M2 table being queries
- `query_id` : a non-human-readable hash of query structure
- `name` : a human-readable name for the query
- `description` : a longer human-readable description of the query
- `facets` : a JSON blob encoding facet configuration

To produce a navigable link to a query result page, we'd have to handle three parts:
- choose a catalog ID, perhaps the default public catalog `1`?
- apply the chaise-specific serialization of the facets blob (JSON serialization -> compression -> base64)
- assemble a recordset URL via templating from these pieces

This could be done within a Chaise page via handlebars templateing in a custom display hint for the saved query table. The same logic can be replicated in a custom dashboard page.

**Comment by victor73** [comment]
The design calls for having the creation date, and last execution date. Can those be added as well?

**Comment by karlcz** [comment]
Sure, but shall we make it timestamps?  I think the presentation
layer could truncate to date, but we can't change our minds
if we don't store with more precision...

**Comment by victor73** [comment]
Ah, yes, I should have clarified. The timestamps should be stored with a precision of seconds (at least). The UI can then perhaps display the increased precision with a rollover/tooltip.

**Comment by karlcz** [comment]
Actually, we already have a system-maintained "RCT" (row creationt
timestamp)... could we use that for query creation time?

Then, we only have to worry about last execuition time which is
a different concept from row modificaton time. E.g. when we apply
the saved filters in recordset, not when the user revises the
human-readable name, description, etc.

When we apply a saved query from the menu inside recordset, we'd
certainly be able to report back a new execution time. But, to do it
when arriving via a navigation link, we'll need to add some extra
context to link back to the saved query record. (Not every link
to recordset w/ attached filters is a saved query application.)
So, it seems like we'll have to also modify the URL template to form
these navigation links for saved queries. This will be some extra
work we didn't realize we needed this cycle...

**Comment by victor73** [comment]
Okay, I suppose we'll need to report this. Or possibly modify the design to exclude the the execution time.

**Comment by jrchudy** [comment]
From a conversation in slack that never got into the github issue, we need to append `?savedQueryRid={{rid}}` to the end of the links to apply the saved queries so the last execution time can be updated.

A modification to Karl's url above:
```
/chaise/recordset/#{{catalog_id}}/{{schema_name}}:{{table_name}}/*::facets::{{encoded_facets_blob}}?savedQueryRid={{rid}}
```
