### ISSUE TITLE
Content summary plots should be interactive

### ISSUE THREAD

**Issue by ACharbonneau** [nih-cfde/dashboard#60]
Currently plots for review are just one static plot https://app-staging.nih-cfde.org/dcc_review.html?catalogId=49

It would be nice if they could be interactive like the landing page plot https://app-staging.nih-cfde.org/

**Comment by jonathancrabtree** [comment]
@ACharbonneau I don't know who decided that it shouldn't be interactive, or why, but it should be an easy thing to change. It does look like the width of the chart panel is constrained to be narrower than the one on the landing page, but I think the dropdown menus should still fit. In terms of layout I presume that the Data Review panel should be extended vertically to match the newly increased height of the Data Snapshot panel.

**Comment by jonathancrabtree** [comment]
Failed to observe correct tagging/closing etiquette on this issue, but this change should be included in tomorrow's release. I had to increase the height of the top panels a little. The starting configuration for the chart is the same as before, but now it can be changed, just like the landing page.

**Comment by ACharbonneau** [comment]
Could we drop the 'CF Program' option from the dropdowns? These are defacto always just one DCC, and it breaks the plot if you use it:

![image](https://user-images.githubusercontent.com/1719360/109539859-c6411c80-7a8f-11eb-8986-c47c1ec19efa.png)

**Comment by jonathancrabtree** [comment]
This change will also be included in Epic 2 RC2.

**Comment by jonathancrabtree** [comment]
@ACharbonneau, can this be closed? I believe it's in production and has passed testing (except for #63.)
