### ISSUE TITLE
Color legend error in staging on dcc_review.html

### ISSUE THREAD

**Issue by jonathancrabtree** [nih-cfde/dashboard#63]
Summary chart sometimes (but not always) loads like this on staging:

![Screen Shot 2021-03-01 at 3 35 49 PM](https://user-images.githubusercontent.com/5394345/109555765-f1356b80-7aa3-11eb-997a-9e5014d4a3f3.png)

**Comment by jonathancrabtree** [comment]
Was able to replicate the bug on app-dev also. It looks like an interaction of two things that should both be addressed even if one is sufficient to resolve the issue:

1. The page CSS causing the chart panel to bounce around the page a couple of times before settling on its final location and size (note that this only happens if the Chaise/navbar-included CSS is present.)
2. The chart not resizing/redrawing at the right time (or at all?) to match its container (unlike, for example, summary_graph.html, where the chart resizes correctly and we don't seem to see the same artifact in the color legend.)

**Comment by jonathancrabtree** [comment]
I've removed the temporary workaround and committed what I hope is a better long-term fix. The issue is that all of the nested flex elements were causing the layout to bounce around as the JavaScript code added content dynamically to the page. I tried a variety of different things to try to get it to remain stable and ended up just forcing the width of one of the containing divs to the value it seemed to be constrained to anyway. My testing was done without the full navbar code/CSS in place, so it's not 100% guaranteed to work, but I'm guardedly optimistic nonetheless.

**Comment by jonathancrabtree** [comment]
This is definitely not working on app-dev (and removing the workaround has made the problem significantly worse). There's something in the navbar CSS that's causing the layout to jump around still. It works on my development box, but only because I don't have a full Chaise install. Hold off on testing until I've taken another crack at fixing this.

**Comment by jonathancrabtree** [comment]
I've copied one of the style directives over from custom.css and inserted it as an inline style in dcc_review.html. It doesn't completely solve the unstable layout problem but it seems to reduce it to the point where it doesn't affect the chart rendering. It may be that simply waiting for the page to finish loading (completely) before drawing the chart is the better solution but the unstable layout is something we'd probably still want to eliminate regardless. I'm guessing the instability may have something to do with the fact that the navbar and its associated CSS files are getting inserted into the page after some of the layout has already been done. I'm hesitant to mess with the CSS/layout too much since I didn't do the original design and this fix/workaround simply takes the existing workaround and makes it less sensitive to the order in which the various files are loaded.

**Comment by jonathancrabtree** [comment]
@ACharbonneau, @jrchudy I believe this was fixed in the last release. I didn't close the case because I thought that was the testing teams's prerogative for anything marked "testing". (The issue didn't go away completely, but it became a problem with the download button, which is tracked in #76.)

**Comment by ACharbonneau** [comment]
sorry, I think I missed it because it wasn't in the march release epic
