### ISSUE TITLE
Implement cache-busting mechanism for releases.

### ISSUE THREAD

**Issue by jonathancrabtree** [nih-cfde/dashboard#64]
Client browsers won't necessarily pick up new releases of the client-side dashboard JavaScript code right away because there's no built-in cache-busting mechanism. A simple solution would be to add some version-dependent suffix, prefix, or path component to the dashboard JavaScript files so that each new release appears to the client as an entirely new set of JavaScript (and CSS) files. See https://github.com/nih-cfde/cfde-deriva/issues/155 for an example of the problem.

**Comment by jonathancrabtree** [comment]
@jrchudy mentioned that DERIVA doesn't modify the actual source JavaScript filenames but appends a suffix to them when the client makes a request e.g., http://someserver/js/library.js?ts=03052021. This seems like a good approach and we could use some logical identifier that's tied to the GitHub release so that it changes only when (some part of) a new dashboard release is created. Some care may need to be taken to ensure that CFDE users who have viewed the code in dev and/or staging (where perhaps multiple dev releases might otherwise share the same id) also get their cache cleared when they view the final release in production.

**Comment by jrchudy** [comment]
This is a change that should be applied to each of the assets used in dashboard repo when that content changes. In deriva, we append `?v=MMDDYYYYhhmmss` at build time, before pushing all of the scripts and assets to the server.

**Comment by jonathancrabtree** [comment]
Wrote a ran a script that will add a timestamp suffix to each reference to a JavaScript file in the dashboard repo. It works by using git log to determine when each file in question was last updated. Next step is to have it run automatically as a pre-commit hook.

**Comment by jonathancrabtree** [comment]
The script actually needs to be a post-commit hook, since it updates timestamps based on last commit time. This makes updating the timestamps a 2-step process (1. commit new JS files, 2. commit the files that reference them) but it doesn't take long and the git hook _could_ be modified to auto-commit after updating the timestamps if a developer prefers that approach. I haven't put the hook script into the repo because I don't know how the current build/install process will handle such extraneous files.

@jrchudy, I think the only outstanding issue here is what you want me to do about the references to the chaise .js files in the following dashboard files:

```
dashboard.html:    <script src="./chaise/lib/navbar/navbar.app.js"></script>
dcc_review.html:    <script src="/chaise/chaise-config.js"></script>
index.html:    <script src="./chaise/lib/navbar/navbar.app.js"></script>
```

My script doesn't work on these files because they are not in the same GitHub repo. Also, I'm not sure if I was the one who made some of those links "./chaise" and some of them "/chaise" but it might be good to standardize on one.

**Comment by jonathancrabtree** [comment]
@jrchudy do you think this case can be closed? I recall that Karl didn't like the way it was being done, but as far as I know it does what it's supposed to and I'd be inclined to put whatever work needs to be done to improve it in a new issue if needed.

**Comment by jrchudy** [comment]
I agree. We can close this issue and open another one for improving on this process for the few other assets not being cache controlled properly.
