### ISSUE TITLE
One of the three links to "Projects" on dcc_review.html is incorrect.

### ISSUE THREAD

**Issue by jonathancrabtree** [nih-cfde/dashboard#65]
There are three identical links to "Projects" on dcc_review.html. The one under "Data Breakdown" is incorrect and has the super-project set to an empty value instead of the correct super-project (i.e., the one that represents the DCC itself.)

**Comment by ACharbonneau** [comment]
I’ve made a public error and issue tracker: https://github.com/nih-cfde/published-documentation/discussions it’s part of the extant repo that hosts the documentation website. I'm noting this there: https://github.com/nih-cfde/published-documentation/discussions/156

**Comment by jonathancrabtree** [comment]
Fixed, but requires both dashboard-api and dashboard to be pushed to devel.

**Comment by jonathancrabtree** [comment]
@ACharbonneau can this be closed yet?

**Comment by ACharbonneau** [comment]
updated bug tracker
