### ISSUE TITLE
provenance report doesn't exist

### ISSUE THREAD

**Issue by ACharbonneau** [nih-cfde/dashboard#66]
This is a hold over from the wireframes that we never filled with information. We should find something to put in it, or just drop it from the summary chart page.

I’ve made a public error and issue tracker: https://github.com/nih-cfde/published-documentation/discussions it’s part of the extant repo that hosts the documentation website. I'm noting this there: https://github.com/nih-cfde/published-documentation/discussions/157

**Comment by jrchudy** [comment]
![image](https://user-images.githubusercontent.com/2932600/110983335-79c2d000-831e-11eb-8a26-bf03d3feea5a.png)

On dcc_review.html

**Comment by jonathancrabtree** [comment]
It's not clear that we have much in the way of provenance information, at least not beyond what's already in the registry database (i.e., who loaded it, when, and from what datapackage). This is all information that can already be seen on the "Data Review" page, although it may be useful to repeat on this page too. Whether it should be called a "Provenance Report" when it's labeled "Submission" on the other page is another question. Is there anything I'm not thinking of that could go into a Provenance Report? I don't think our current schema models anything like a "source database", and in any case that's likely to be simply the DCC itself for the data we currently have.

**Comment by ACharbonneau** [comment]
I don't think we really have anything to go there right now. I think eventually we might, but I'm leaning towards deleting it until we actually have something useful to put there

**Comment by jonathancrabtree** [comment]
We could remove the Provenance box and allow the Report Issues box to expand to full the width of the right-hand panel:

![Screen Shot 2021-03-25 at 4 21 43 PM](https://user-images.githubusercontent.com/5394345/112538511-4e140100-8d86-11eb-8b6d-c2d6035a3468.png)

Or keep Report Issues the same and remove/hide Provenance:

![Screen Shot 2021-03-25 at 4 28 52 PM](https://user-images.githubusercontent.com/5394345/112539408-57ea3400-8d87-11eb-8bc0-73abf03b28a2.png)

Or something else (e.g,. left-justify the Report Issues box so it's right up against the left margin.)

**Comment by ACharbonneau** [comment]
ooh! Here's an idea, what if we change "Report Issues" to "Contact the helpdesk (but leave the link the same), add replace the provanance box with one that says "Submit a feature request" and link here: https://github.com/nih-cfde/published-documentation/discussions ? 

And maybe add a third one that says "How to Guides" and links to both [How to review your datapackage](https://github.com/nih-cfde/published-documentation/wiki/How-to-review-a-datapackage) and [How to approve your datapackage](https://github.com/nih-cfde/published-documentation/wiki/How-to-approve-your-datapackage)

**Comment by jonathancrabtree** [comment]
Two boxes:

![Screen Shot 2021-03-25 at 8 08 10 PM](https://user-images.githubusercontent.com/5394345/112560926-8cbbb280-8daa-11eb-85b1-3434baad07e0.png)

Three boxes, plus I centered everything horizontally to match the layout of index.html a little more closely. Personally I like the 3-box layout, and also the fact that as you go from left to right you're kind of escalating the support request (i.e., step 1 = read the manual, step 2 = file an issue on the tracker, step 3 = e-mail a live person directly). I've tweaked the wording a bit, so just let me know if you prefer something else. I was trying to make the title and the content of the boxes at least slightly different, with the latter being more verbose:

![Screen Shot 2021-03-25 at 8 41 43 PM](https://user-images.githubusercontent.com/5394345/112561012-b5dc4300-8daa-11eb-8461-4dd689f7cb34.png)

**Comment by jonathancrabtree** [comment]
I take back what I said about the horizontal centering; checking against app-dev and app it seems that only the dashboard page has its content centered. On index.html (the landing page) and dcc_review.html the main content is left-justified slightly to the left of the heading block ("Common Fund Data Ecosystem / Human Microbiome Project (HMP) / etc."). Here are those two pages as currently seen on app.nih-cfde.org. Note that the 3 boxes at the bottom (on index.html) span the entire width of the page:

![Screen Shot 2021-03-26 at 8 44 50 AM](https://user-images.githubusercontent.com/5394345/112633342-9f1c0780-8e0f-11eb-913d-6864f5ac62e8.png)
![Screen Shot 2021-03-26 at 8 45 05 AM](https://user-images.githubusercontent.com/5394345/112633358-a4795200-8e0f-11eb-9140-b6b141e05ff0.png)

Adjusting dcc_review.html to match those pages, we get this layout:

![Screen Shot 2021-03-26 at 8 46 51 AM](https://user-images.githubusercontent.com/5394345/112633551-dd192b80-8e0f-11eb-88a8-c951c3449fe8.png)

**Comment by ACharbonneau** [comment]
I liked it with the three box centering. I think the front page would actually look nicer if we made it do that rather than making the report view page have the weird centering (but I can make a separate issue about that) Also +1 on updated wording.

**Comment by jonathancrabtree** [comment]
How's this for the landing page/index.html:

![Screen Shot 2021-03-26 at 3 22 09 PM](https://user-images.githubusercontent.com/5394345/112692491-6acb3a00-8e55-11eb-964e-7f8e2e7894a5.png)

**Comment by ACharbonneau** [comment]
I like it. Does it render okay on smaller devices? I can't remember what our minimum support size is but i think it's ~regular ipad

**Comment by jonathancrabtree** [comment]
It does, assuming we're talking about a not-ancient iPad in landscape orientation. Chrome Developer tools lists the "iPad Pro" as having a resolution of 1024 x 1366 and it looks like both the current landing page (app.nih-cfde.org) and the proposed new one (with content centered) look OK at widths of ~1300 pixels and above. So in landscape mode we're good and my guess is that this was the original intent (to support 1366 pixels wide) At 1024 pixels wide it's not so good for either the current version or the proposed new version.  Below 1300 you start to lose content off the sides and layout glitches begin to appear (e.g., the summary counts box in the top right corner gets bumped onto the next line and hidden behind the "Explore our Repository" box.) As you drop the width down things get worse for both the current and proposed new version although the current version has the advantage that things only overflow to the right; with the content centered you get overflow on both left and right. 

New/proposed version in landscape and portrait at 1366x1024:

![Screen Shot 2021-03-26 at 5 28 45 PM](https://user-images.githubusercontent.com/5394345/112694474-d367e600-8e58-11eb-8a1e-62d31521e244.png)
![Screen Shot 2021-03-26 at 5 29 04 PM](https://user-images.githubusercontent.com/5394345/112694489-d82c9a00-8e58-11eb-9dbf-9a0852e2d4a0.png)

Same for current version:
![Screen Shot 2021-03-26 at 5 31 46 PM](https://user-images.githubusercontent.com/5394345/112694743-41aca880-8e59-11eb-8efe-f7e04b5e7f81.png)
![Screen Shot 2021-03-26 at 5 32 23 PM](https://user-images.githubusercontent.com/5394345/112694754-46715c80-8e59-11eb-9dc0-5b67eec506a9.png)

**Comment by jonathancrabtree** [comment]
I'll throw in a media query to disable the content centering below 1300px and then we'll have the best of both worlds.

**Comment by jonathancrabtree** [comment]
New new version. Also threw in a quick fix for the summary box wraparound issue, so even at 1024px wide it should look reasonable:

![Screen Shot 2021-03-26 at 6 09 19 PM](https://user-images.githubusercontent.com/5394345/112697745-9f8fbf00-8e5e-11eb-8e21-56651ec4c493.png)
![Screen Shot 2021-03-26 at 6 12 08 PM](https://user-images.githubusercontent.com/5394345/112697836-cfd75d80-8e5e-11eb-88e4-8d372212a2f2.png)

**Comment by jonathancrabtree** [comment]
Not sure what's up with that vertical white bar in the far bottom right. Looks like the navbar overhangs the page body by a few pixels on the right. It's not present on app.nih-cfde.org but it may be due to some navbar-related style change.

**Comment by jonathancrabtree** [comment]
@ACharbonneau I believe this issue can be closed. I've created a new one (#79) for the more general issue of making sure that all of the pages are properly responsive.

**Comment by ACharbonneau** [comment]
yep. same as the other one. epic 2 tech debt was in march data release, but then we pulled it out so we could just tie in individual issues and it looks like we missed some
