### ISSUE TITLE
Dashboard chart allows users to choose incompatible options, errors badly

### ISSUE THREAD

**Issue by ACharbonneau** [nih-cfde/dashboard#67]
See https://github.com/nih-cfde/published-documentation/discussions/172 for screenshot.

If you choose "Data Type" in the 'Stack by' dropdown, it does not grey out "Data Type" in the 'X-axis' dropdown, and the chart can't render. The error message doesn't tell them they've chosen an impossible chart, so they don't notice the problem.

**Comment by jonathancrabtree** [comment]
This is definitely a regression and I was able to replicate it on both dev and production. The auto-exclusion feature works correctly but only in one direction: if you select an option from "X-axis" on the left then the corresponding entry in "Stack by" on the right will be greyed out correctly:

![Screen Shot 2021-03-09 at 12 17 07 PM](https://user-images.githubusercontent.com/5394345/110511970-c914c080-80d2-11eb-867c-1d97d32924ae.png)

However, if one first selects an option from "Stack by" then the corresponding one in "X-axis" does not get disabled/greyed out as it should:

![Screen Shot 2021-03-09 at 12 17 48 PM](https://user-images.githubusercontent.com/5394345/110512266-0ed18900-80d3-11eb-9171-79495a62cefc.png)

**Comment by jonathancrabtree** [comment]
Should be fixed (but not yet on app-dev, which is also currently out of commission):

![Screen Shot 2021-03-22 at 10 39 07 AM](https://user-images.githubusercontent.com/5394345/112007272-e7c77e00-8afa-11eb-89a2-60409932d6c2.png)

**Comment by ACharbonneau** [comment]
This looks good, but I need to update the bug report before closing

**Comment by jonathancrabtree** [comment]
@ACharbonneau can this be closed yet?

**Comment by ACharbonneau** [comment]
updated bug tracker thing
