### ISSUE TITLE
GTeX and KFDRC have no data for 2nd Dashboard donut chart.

### ISSUE THREAD

**Issue by jonathancrabtree** [nih-cfde/dashboard#75]
Selecting either GTeX or KFDRC for the "Samples by Anatomy and CF Program" donut chart on the Dashboard gives a blank chart, presumably because the corresponding data weren't loaded for these two programs in the new release catalog. All the other choices seem to work fine:

![Screen Shot 2021-03-29 at 4 25 47 PM](https://user-images.githubusercontent.com/5394345/112988247-9ee27b80-9131-11eb-91c5-945983c04708.png)

Not sure if it's better to:

-  leave it as-is (otherwise people may interpret the absence of just these two DCCs from the list as a bug
-  remove DCCs from the list if they don't have the necessary data
-  display some error message to indicate that this is a known issue and it's because the data aren't yet available in CFDE

**Comment by ACharbonneau** [comment]
I assumed the choices were pulled from the available columns of the data :/ If they are coded in, we should add a step to releasing a new catalog where we rebuild these tables or code or whatever to match the new data. I think @karlcz has some kind of 'what needs to happen for release' checklist that it can get added to.

for the moment tho, those two shouldn't be options, because they just didn't put any anatomy data in.

**Comment by jonathancrabtree** [comment]
@ACharbonneau the choices are pulled from the database, but only in the sense that it looks at what DCCs are loaded. It doesn't check whether those DCCs submitted the data necessary to make that _particular_ plot because, frankly, when I was adding the feature in Epic 2 it didn't occur to me that the underlying database might not have the data needed to display the plots that the folks designing the interface were telling us had to be supported... This is essentially the same issue as the one about the charts/plots not being very useful for level 0 C2M2 submissions. I'll check and see if there's a quick way to fix this without reverting to a hard-coded list of DCCs on that page.

**Comment by jonathancrabtree** [comment]
Fix is in the latest .4 release. DCCs without any data for the donut chart won't appear in the dropdown.

**Comment by ACharbonneau** [comment]
good in staging
