### ISSUE TITLE
Create page for Personalized Dashboard

### ISSUE THREAD

**Issue by jonathancrabtree** [nih-cfde/dashboard#78]
Link to design:
https://drive.google.com/file/d/1i2F5zgM65-Ksh1xrqcGd0S8sl-5uNvlX/view

Additional info/requirements from design team:
-  Clicking on saved query will re-run that query in Chaise
   - The link that should be used should look something like:
      - `"/chaise/recordset/#1/" + row.schema_name + ":" + row.table_name + "/*::facets::" + row.encoded_facets + "?savedQueryRid=" + row.RID;`
-  The Graph at the bottom should show only data from the DCCs selected in the box to its right
-  Initially the set of selected DCCs should match the current user's Favorite DCCs
-  Selecting/deselecting DCCs in this box will not alter the user's favorites, but it will change what is displayed in the Graph
-  Whatever the user selects for x-axis, y-axis, and stack-by (i.e., the Graph dropdown boxes) should be remembered from one login to the next (i.e., stored in the user's profile)
-  Same for the checked DCCs to the right of the graph.

**Comment by jonathancrabtree** [comment]
Created personalized dashboard page with empty placeholders for the yet-to-be-created widgets (#49, #77):

![Screen Shot 2021-04-15 at 11 53 01 AM](https://user-images.githubusercontent.com/5394345/114899700-30fcac00-9de1-11eb-9515-80b9d2dbe9d8.png)

The planning document doesn't say much about which dashboard users see if they _haven't_ logged in, but one possibility is to show them a version of the personalized dashboard with the personalization features disabled (i.e,. effectively letting them know that if they were to log in and provide some information then they'd get an upgraded experience.) In this case the new personalized dashboard page (pdashboard.html) will replace the existing one (dashboard.html) but until that's finalized we'll keep them separate.

The checkboxes are populated based on the DCCs in the source catalog, but they don't do anything yet - making the graph reflect a subset of the DCCs is actually something that the current API/backend does not support and that will have to be scoped out in the appropriate repos.

**Comment by jrchudy** [comment]
From our discussion in the UX call today, we noted that the personalized dashboard design that we received is only a template or rough draft. It's only meant to convey the ideas we want and not be the final design.

With that being said, we want to consider 2 more cases for the "dashboard" page. Do we want to remove the dashboard page and use the new personalized dashboard for logged out and logged in users?
  - we decided that we want to show the saved searches and favorites boxes to logged out users as a suggestion to "maybe" login to use more features
  - also helps communicate that they aren't currently logged in

We need to include the carousel in the layout of the personalized dashboards as well. Should the carousel be below or above the currently displayed graph widget?
  - unsure at the moment as to what would look better

And the last bit, we want to be able to save the configuration of the currently displayed graph including selected DCCs and axis options. 
  - By default the DCCs that are selected will be the users "favorite" DCCs (so 1 or more)
  - if no favorite DCCs exist, default to using the DCC(s) the user is associated with
  - if DCCs are selected or deselected and axis options changed, we want to save that configuration so it can be shown on loading the personalized dashboard next time the current user navigates there
    - Should this save be automatic after ~5 seconds? 
    - Should it be a control the user has to initiate to "save" the configuration?
    - Should saving also save the selection in favorites?
      - by default we show favorite DCCs
      - if user selects the favorite anatomies tab (and saves), does that change the default view for the favorites widget?
   - saving the configuration will be done in a jsonb column noted in _this pending issue in CFDE-deriva_

**Comment by jrchudy** [comment]
The [proposed model](https://github.com/nih-cfde/cfde-deriva/blob/db_scaling/README-registry.md) for the saved query and favorites tables.
