### ISSUE TITLE
Changes to static pages from Interface Guru feedback

### ISSUE THREAD

**Issue by jrchudy** [nih-cfde/dashboard#90]
Link to folder with wireframes:
https://drive.google.com/drive/u/1/folders/1crbuUEujulc9Pze9zdDFH_6CToUhKUHu

Changes to the homepage that will be handled during Epic 3:
 - [x] Change the default x-axis selection to "Data Type" instead of "CF Program"
    - homepage AND dashboard page
    - update chart on https://www.nih-cfde.org/ also
    - update the chart on data review to have the same default axis, Data Type, File, and Assay
 - [x] Add new dccs (2 new ones)
    - Logos for the homepage in the bottom left box
 - [x] wording/link changes
    - change the titles of each box on the homepage
      - "Explore our Repository" -> "Start your Search"
      - "Summary View" -> "Preview the data"
      - "Participating Common Fund Programs" -> "Searchable Common Fund data sets"
 - [x] Make the links/button work
    - Fix "search all files" button

**Comment by jonathancrabtree** [comment]
@jrchudy , @ACharbonneau, can either of you remind @mschor and I what the "Search all files" button is supposed to do? It doesn't seem to be working on either app or app-dev and my best guess is that it's supposed to do exactly the same thing as clicking on the "File" link under "View Data By" immediately below (raising the obvious question "Why have both?")

The JavaScript code seems to back up this interpretation, although I have not yet determined why it's not working:

```
    // "Search all Files" button                                                                                                                                                     
    $('#search-all').click(function() {
        location.href = '/chaise/recordset/#' + catalog_id + '/CFDE:file';
    });
```

For reference here's the HTML for the "View Data By" links:
```
                <h4>View Data By</h4>
                <ul>
                  <li><a href="/chaise/recordset/#1/CFDE:collection" target="_blank">Collection</a></li>
                  <li><a href="/chaise/recordset/#1/CFDE:biosample" target="_blank">Biosample</a></li>
                  <li><a href="/chaise/recordset/#1/CFDE:subject" target="_blank">Subject</a></li>
                  <li><a href="/chaise/recordset/#1/CFDE:file" target="_blank">File</a></li>
                </ul>
```

**Comment by jrchudy** [comment]
I don't know where our conversation about the "Search all Files" button occurred before, but I believe that is supposed to be the expected behavior. Not sure why we have both going to the same place though, that can be a discussion for Friday.

**Comment by jonathancrabtree** [comment]
Changed default x-axis selection from "CF Program" to "Data Type" on dashboard home page (index.html), old/deprecated dashboard page (dashboard.html) and summary graph page included on main home page (summary_graph.html):

![Screen Shot 2021-08-17 at 10 58 34 AM](https://user-images.githubusercontent.com/5394345/129751738-70fe6fa3-5176-4a81-8838-e869f9ed0245.png)

**Comment by jonathancrabtree** [comment]
Also updated dcc_review.html to use Data Type/File/Assay:

![Screen Shot 2021-08-17 at 11 11 02 AM](https://user-images.githubusercontent.com/5394345/129752648-5dbe2099-ac44-42cc-9dcf-e32c6da662f0.png)

**Comment by jonathancrabtree** [comment]
Changed wording as specified:

![Screen Shot 2021-08-17 at 11 19 56 AM](https://user-images.githubusercontent.com/5394345/129753950-798e778d-cc22-4040-8f0d-16b18000252c.png)

I've used the exact capitalization given, although it's not immediately clear to me why we're capitalizing words like "Search" and "Media" in the headings, but not "data" or "sets". Also, since we seem to be standardizing on "data set" versus "dataset" I'll also update "Search over 100,000 datasets from across the Common Fund" to match. It looks like this is the only occurrence of "dataset" in dashboard.

**Comment by jonathancrabtree** [comment]
SEARCH ALL FILES button should work now. The heading reads "Make the links/button work" but there's no mention of any broken links and it seems as though they're working on app.nih-cfde.org. The only question is whether it's safe to assume that catalog 1 will always be the current release catalog.

**Comment by jonathancrabtree** [comment]
Looks like the two new DCCs are as follows:

- IDG - Illuminating the Druggable Genome - https://www.druggablegenome.net
- SPARC - Stimulating Peripheral Activity to Relieve Conditions - https://sparc.science

**Comment by jonathancrabtree** [comment]
Added IDG and SPARC logos to home page:

![Screen Shot 2021-08-17 at 4 38 25 PM](https://user-images.githubusercontent.com/5394345/129797247-59431c0a-a76f-43c3-9209-ee35be8c71fa.png)

**Comment by jonathancrabtree** [comment]
These changes are now live on https://app-dev.nih-cfde.org

**Comment by ACharbonneau** [comment]
Hey @jonathancrabtree 

For the capitalization, I don't have an explanation. If "Social media" looks better thats fine. 

I'm sorry I missed it in the original info, but could we also update the title text:
![image](https://user-images.githubusercontent.com/1719360/130678827-48fcc9c0-cbad-4894-9352-10024298df76.png)


And we want to entirely delete the sentence "Search over 100,000 datasets from across the Common Fund"
