### ISSUE TITLE
Dcc Review page has broken subtitle

### ISSUE THREAD

**Issue by jrchudy** [nih-cfde/dashboard#93]
When looking at the [dcc_review page for catalog 397](https://app-dev.nih-cfde.org/dcc_review.html?catalogId=397), I see the submitted datapackage subtitle is missing info:
![image](https://user-images.githubusercontent.com/2932600/130133442-b360d490-2032-4f3d-9a5f-0445034ed422.png)

The link for the external icon also seems to be misconfigured now. It points to the page we are currently on (instead of the portal for that catalog (https://app-dev.nih-cfde.org/chaise/recordset/#397/CFDE:file)

Another issue here is that the "external link icon" should not be used since this is intended to be a navigation within the app.nih-cfde.org application.

**Comment by jonathancrabtree** [comment]
I noticed this earlier and was about to file an issue. It looks like both the missing/incorrect link and missing counts are due to a failed API call. I assume app-dev is running the db_scaling branch of dashboard-api?

**Comment by jonathancrabtree** [comment]
@mschor confirms that app-dev is running db_scaling branch of dashboard-api. The underlying error here is the following:

Target app-dev.nih-cfde.org catalog 'registry' lacks the required CFDE.core_fact table

Instantiating DashboardQueryHelper on the registry db is no longer a supported operation, so the dashboard-api code was modified to use ErmrestCatalog directly instead.

**Comment by jonathancrabtree** [comment]
Also removed inappropriate external link icon. Changes should be on app-dev by tomorrow and ready for testing.

**Comment by jonathancrabtree** [comment]
Still seeing the error on app-dev this morning, but have no way to check if/when the app-dev dashboard-api host was last updated with the db_scaling branch.

**Comment by jonathancrabtree** [comment]
dashboard-api was just updated and this looks good to me on app-dev:

![Screen Shot 2021-08-20 at 12 43 01 PM](https://user-images.githubusercontent.com/5394345/130266820-49bb754e-eea5-4007-9634-344782baed78.png)

**Comment by jonathancrabtree** [comment]
This is an aside, but the method I was using previously to estimate a "last_updated" time is no longer viable. We'd removed those timestamps from all the pages except this one anyway. The timestamp now shown on this page is pulled from the registry database and it's using the datapackage.submission_time, which seems reasonable but perhaps the API and this page should at some point be updated to make this explicit.

**Comment by jrchudy** [comment]
Looks like this has been fixed on dev (and production). Closing this issue
