### ISSUE TITLE
Update wording

### ISSUE THREAD

**Issue by ACharbonneau** [nih-cfde/dashboard#95]
![image](https://user-images.githubusercontent.com/1719360/130816678-4153505b-b649-41b5-9512-9f57902fbe57.png)

There is no "saved queries' button in the upper-right corner of this screen

**Comment by jonathancrabtree** [comment]
I know this probably came up at last week's meeting but I don't remember the exact requirement. @ACharbonneau are you saying you want the "Saved queries" dropdown from Chaise on this dashboard page too (but with the "Save Query" option removed, I assume?):

![Screen Shot 2021-08-25 at 11 28 31 AM](https://user-images.githubusercontent.com/5394345/130820045-8a00a00e-4f0c-48ca-be88-8db60d26a263.png)

If so it seems like there might be a few potential issues:

- It's a little strange to have a dropdown with only a single choice.
- The "Show saved queries" option in Chaise is table-specific i.e., it shows you only the saved queries for the table you're currently looking at.
- If you want the saved queries to appear as a Chaise table/popup (i.e., same way it works in Chaise) I'm not sure whether we're currently loading enough of the Chaise JavaScript code on the dashboard pages for this to work. @jrchudy may be able to answer this, but it seems like maybe a tighter dashboard/Chaise integration than we've attempted thus far?
- You're already on a page that shows the saved queries (albeit paginated). As a user a link like "show all saved queries" or "show detailed saved query view" might make sense, but "show saved queries" alongside a table labeled "saved queries" not so much.

**Comment by mschor** [comment]
I think the confusion was possibly just in the wording choice that I used. I had written, "browse the portal data and click the 'saved queries' button." Maybe there's a better way to say this. Or maybe just saying, "You don't have any saved queries." would be sufficient. A user won't see that drop down that Jonathan posted when navigating the dashboard; only when browsing the data portal.

**Comment by jonathancrabtree** [comment]
@ACharbonneau no the confusion is that even with my glasses I couldn't read the text in the "Saved Queries" box in the default image size. Sorry for being an idiot! I see what you're saying.
