### ISSUE TITLE
IDG should be capitalized- update documentation for display names

### ISSUE THREAD

**Issue by ACharbonneau** [nih-cfde/dashboard#96]
![image](https://user-images.githubusercontent.com/1719360/130817471-448be966-17ee-42c8-8e42-c99c0e0626c4.png)

**Comment by jonathancrabtree** [comment]
Agreed, but I'm not sure that's a dashboard bug. Are you saying you want the entire UI to override the DCC's submission (in which, at least in one field, "idg" was not capitalized)?

![Screen Shot 2021-08-25 at 11 21 31 AM](https://user-images.githubusercontent.com/5394345/130818653-023ba295-43e4-4281-91bc-175b192457c4.png)

Maybe the simplest thing to do is just have an admin tweak the "abbreviation" in the following record in the database?

https://app-staging.nih-cfde.org/chaise/record/#1/CFDE:dcc/nid=5

Ideally I guess this would have been caught by CFDE review before the submission found its way into the release catalog, although it is a pretty minor thing to force a resubmission over.
